version: "3"
services:
  app:
    image: node:alpine
    volumes:
      - ./:/app
      - notused:/app/node_modules
    working_dir: /app
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
    command: npm run dev
  mongo:
    image: mongo
    environment: 
      MONGO_INITDB_DATABASE: misap_DB
    expose:
      - 27017

volumes:
  notused: